
import Header from "@/header/header";
import "./globals.css";
import 'rsuite/dist/rsuite.min.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header/>
      <main>{children}</main>
      <footer className="bg-gray-800 text-white p-4 text-center bottom-0 w-full">
        Footer
      </footer>
      </body>
    </html>
  );
}
